travis:
  secure:
    BINSTAR_TOKEN: N9nAKXV0oHe+hBgSE4EedYZ3CvsQeQGFURuzywaHHyQOBM1IfOmsDjxWfs6IznNsKKxBId15HoOWQiptd6L70qyJstPuhUzMOLltsxwEZ+rijOEfeh1AptrEt+A/vi++Uks8S0TuToaxcxOYws22zuCVybsOft+EPPAFX3Tv+Bupe2uosf9gCZ7gtyde3JEzADQYqgLtD8tL6o4rW4So8GfGGZUCSk6gM2kUKm2xtwFD0XuZELmU0dDCQ92wDxc7fM/UrSTu97OTWeUiAvg8603auBOZm4oIXw5qmFhhasb+IFb87WTpgBZL26RYzH22YfEwHZJN/YTDJSTLngw8Zj+Cjrtzv5WGTWRAHGR+8SNbunDbx5AOtQLS2yOcrmnzJtIOvagpSChMFY6YH+TBkQq8A31RGpPFwDW5/ZOGGqQbudVkBMWoaLiLnKF0RkquIFJbUQKKuK4LXTYRL+/Be0dULvZkyRwljZePaYvAmIr/w4fY0nq/1R8DC+seLBdIZJf0Cph2dqg7jKNewZbUfz5r4OIxjZm+sDXro7p1KkAbiMLBmtt3UG4BSLoMY3IFcdwAmbHEGrW8/NRMYDvw+NvmhIg15beApdSz53Y2RooVQWt3eTMZTwADxDBYkO6N3W3P0ewQRvZu7D4r5PGQopmcl0oWrnHN1xd9ob+Tb0w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
